select * from cds;
select nome, DataCompra from cds order by nome;
select nome, DataCompra from cds order by DataCompra desc;
select sum(ValorPago) from cds;
select * from cds where idcds = '4';
select m.Nome, c.nome from musica as m inner join cds as c on m.idcds = c.idcds;
select Nome, Artista from musica;
select numero, Nome, Tempo from musica where idcds = '4' order by numero;
select count(*) from musica;
select count(*) from cds;
select nome from musica where Artista = 'Louro josé';
select count(*) from musica where Artista = 'Louro josé';
select nome from musica order by nome asc;
select max(ValorPago) from cds;
select min(ValorPago) from cds;
select * from cds where DataCompra < 2014-01-01;
select * from cds where DataCompra > 2014-01-01;
select * from musica where Tempo > '00:02:00';
select * from musica where Tempo > '00:05:00' order by nome asc;
select Nome, Tempo from musica where Artista = 'Louro josé' order by max(Tempo);